"""
Project Scaffolder Service - Generates complete project structures.
"""

import json
import logging
import os
import shutil

from django.conf import settings

logger = logging.getLogger(__name__)


class ProjectScaffolder:
    """Generates complete project scaffolds for different platforms."""

    def __init__(self):
        self.projects_root = settings.PROJECTS_ROOT
        os.makedirs(self.projects_root, exist_ok=True)

    def create_project(self, name, platform, options=None):
        """Create a new project scaffold."""
        options = options or {}
        project_dir = self.projects_root / name

        if project_dir.exists():
            shutil.rmtree(project_dir)

        os.makedirs(project_dir, exist_ok=True)

        scaffolders = {
            "django": self._scaffold_django,
            "react_native": self._scaffold_react_native,
            "electron": self._scaffold_electron,
            "django_web": self._scaffold_django_web,
        }

        scaffolder = scaffolders.get(platform)
        if not scaffolder:
            raise ValueError(f"Unknown platform: {platform}")

        files = scaffolder(project_dir, name, options)
        return {"name": name, "platform": platform, "path": str(project_dir), "files": files}

    def _write_files(self, project_dir, files):
        for filepath, content in files.items():
            full_path = project_dir / filepath
            os.makedirs(full_path.parent, exist_ok=True)
            with open(full_path, "w") as f:
                f.write(content)
        return list(files.keys())

    def _scaffold_django(self, project_dir, name, options):
        """Generate a Django backend project scaffold."""
        files = {
            "requirements.txt": "django>=4.2,<5.0\ndjangorestframework>=3.14\ndjango-cors-headers>=4.0\ndjango-filter>=23.0\npython-dotenv>=1.0\ngunicorn>=21.0\ncelery>=5.3\nredis>=5.0\npytest>=7.0\npytest-django>=4.5\nfactory-boy>=3.3\n",
            ".env.example": "DEBUG=True\nSECRET_KEY=your-secret-key\nDATABASE_URL=sqlite:///db.sqlite3\nALLOWED_HOSTS=localhost,127.0.0.1\n",
            ".gitignore": "*.pyc\n__pycache__/\ndb.sqlite3\n.env\nvenv/\nstaticfiles/\nmedia/\n",
            "README.md": f"# {name}\n\nDjango backend generated by CodeCraft AI.\n\n## Setup\n```bash\npip install -r requirements.txt\npython manage.py migrate\npython manage.py runserver\n```\n",
        }
        return self._write_files(project_dir, files)

    def _scaffold_react_native(self, project_dir, name, options):
        """Generate a React Native project scaffold."""
        files = {
            "package.json": json.dumps({"name": name, "version": "1.0.0", "dependencies": {"react": "^18.2.0", "react-native": "^0.73.0"}, "devDependencies": {"typescript": "^5.3.0"}}, indent=2),
            "README.md": f"# {name}\n\nReact Native app generated by CodeCraft AI.\n",
        }
        return self._write_files(project_dir, files)

    def _scaffold_electron(self, project_dir, name, options):
        """Generate an Electron desktop app scaffold."""
        files = {
            "package.json": json.dumps({"name": name, "version": "1.0.0", "main": "src/main/main.js", "devDependencies": {"electron": "^28.0.0", "electron-builder": "^24.9.0"}}, indent=2),
            "README.md": f"# {name}\n\nElectron app generated by CodeCraft AI.\n",
        }
        return self._write_files(project_dir, files)

    def _scaffold_django_web(self, project_dir, name, options):
        """Generate a Django web app with templates scaffold."""
        files = {
            "requirements.txt": "django>=4.2,<5.0\ndjango-htmx>=1.17\ndjango-crispy-forms>=2.0\npython-dotenv>=1.0\ngunicorn>=21.0\n",
            "README.md": f"# {name}\n\nDjango web app generated by CodeCraft AI.\n",
        }
        return self._write_files(project_dir, files)

    def list_projects(self):
        """List all generated projects."""
        if not self.projects_root.exists():
            return []
        return [{"name": item.name, "path": str(item)} for item in self.projects_root.iterdir() if item.is_dir()]

    def delete_project(self, name):
        """Delete a generated project."""
        project_dir = self.projects_root / name
        if project_dir.exists():
            shutil.rmtree(project_dir)
            return True
        return False
