"""Models for the AI agent application."""

import uuid

from django.db import models


class Conversation(models.Model):
    """A conversation session with the AI agent."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=255, default="New Conversation")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    system_prompt_override = models.TextField(blank=True, default="")
    platform_context = models.CharField(
        max_length=50,
        choices=[
            ("general", "General"),
            ("django", "Django Backend"),
            ("react_native", "React Native"),
            ("electron", "Electron"),
            ("django_web", "Django Web Templates"),
        ],
        default="general",
    )
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ["-updated_at"]

    def __str__(self):
        return f"{self.title} ({self.id})"


class Message(models.Model):
    """A single message in a conversation."""

    ROLE_CHOICES = [
        ("system", "System"),
        ("user", "User"),
        ("assistant", "Assistant"),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    conversation = models.ForeignKey(
        Conversation, on_delete=models.CASCADE, related_name="messages"
    )
    role = models.CharField(max_length=10, choices=ROLE_CHOICES)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    token_count = models.IntegerField(default=0)
    metadata = models.JSONField(default=dict, blank=True)

    class Meta:
        ordering = ["created_at"]

    def __str__(self):
        return f"[{self.role}] {self.content[:80]}..."


class GeneratedCode(models.Model):
    """Stores code generated by the AI agent."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    conversation = models.ForeignKey(
        Conversation, on_delete=models.CASCADE, related_name="generated_code"
    )
    message = models.ForeignKey(
        Message, on_delete=models.CASCADE, related_name="code_blocks", null=True
    )
    filename = models.CharField(max_length=500)
    language = models.CharField(max_length=50, default="python")
    content = models.TextField()
    platform = models.CharField(max_length=50, default="general")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.filename} ({self.language})"


class AgentCapability(models.Model):
    """Defines a specific capability the agent can perform."""

    name = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    platform = models.CharField(max_length=50)
    prompt_template = models.TextField()
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Agent capabilities"
        ordering = ["platform", "name"]

    def __str__(self):
        return f"{self.name} ({self.platform})"


class SystemPrompt(models.Model):
    """Versioned system prompts for the AI agent."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    content = models.TextField()
    version = models.IntegerField(default=1)
    is_default = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated_at"]
        unique_together = ["name", "version"]

    def __str__(self):
        return f"{self.name} v{self.version}"
